language: ruby
sudo: false
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - ruby-head

gemfile:
  - gemfiles/Gemfile-rails4.2.x
  - gemfiles/Gemfile-rails5.0.x
  - gemfiles/Gemfile-rails5.1.x
  - gemfiles/Gemfile-rails5.2.x

matrix:
  allow_failures:
    - rvm: 2.5.5
      gemfile: gemfiles/Gemfile-rails4.2.x
    - rvm: 2.6.3
      gemfile: gemfiles/Gemfile-rails4.2.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails4.2.x

before_script:
  - 'gem update bundler'
  - 'gem install rake --no-document'
  - 'cd test/dummy; rake db:migrate; rake db:test:prepare; cd ../..'

script:
  - bundle exec rake test
  - bundle exec rubocop

notifications:
  email: false
