language: ruby
sudo: false
rvm:
  - 2.4.7
  - 2.5.6
  - 2.6.4
  - ruby-head

gemfile:
  - gemfiles/Gemfile-rails5.2.x
  - gemfiles/Gemfile-rails6.0.x

matrix:
  allow_failures:
    - rvm: 2.4.7
      gemfile: gemfiles/Gemfile-rails6.0.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails5.2.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails6.0.x

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

before_script:
  - 'gem install rake --no-document'
  - 'cd test/dummy; rake db:migrate; rake db:test:prepare; cd ../..'

script:
  - bundle exec rake test
  - bundle exec rubocop

notifications:
  email: false
