language: ruby
sudo: false
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head

gemfile:
  - gemfiles/Gemfile-rails4.2.x
  - gemfiles/Gemfile-rails5.0.x
  - gemfiles/Gemfile-rails5.1.x

matrix:
  allow_failures:
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile-rails4.2.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails4.2.x

before_script:
  - 'cd test/dummy; rake db:migrate; rake db:test:prepare; cd ../..'

script:
  - bundle exec rake test
  - bundle exec rubocop

notifications:
  email: false
