name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        ruby: [3.1.6, 3.2.7, 3.3.7, 3.4.2]
        gemfile: [Gemfile-rails8.0.x, Gemfile-rails7.1.x, Gemfile-rails7.0.x]
        exclude:
          - ruby: 3.1.6
            gemfile: Gemfile-rails8.0.x

    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Setup database
      env:
        RAILS_ENV: test
        BUNDLE_GEMFILE: ../../gemfiles/${{ matrix.gemfile }}
      run: |
        cd test/dummy/
        bin/rake db:test:prepare

    - name: Run minitest
      env:
        RAILS_ENV: test
        BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}
      run: |
        bin/test

    - name: Run Rubocop
      run: |
        bundle exec rubocop .
